name: wordpress
version: 5.0.0
appVersion: 5.0.0
description: Web publishing platform for building state websites.
icon: https://auth.s3waas.gov.in/sites/default/files/logo.png
keywords:
- s3waas
- dist
home: https://s3waas.gov.in/
sources:
- https://s3waas.gov.in/
maintainers:
- name: Priyaranjan Jena
  email: priyaranjan.653@gmail.com
engine: gotpl
